urls.py
from django.conf.urls import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

entry_id = '(?P<entry_id>\d+)'
person_id = '(?P<person_id>\d+)'
rating_id = '(?P<rating_id>\d+)'
talk_id = '(?P<talk_id>\d+)'
topic_id = '(?P<topic_id>\d+)'
width = '(?P<width>[^/]+)'

urlpatterns = patterns('',
    (r'^$',
        'studyjournal.talks.views.index'),

    (r'^people/$',
        'studyjournal.talks.views.people'),
    (r'^person/'+person_id+'/$',
        'studyjournal.talks.views.person'),
    (r'^person/'+person_id+'/edit$',
        'studyjournal.talks.views.edit_person'),
    (r'^person/'+person_id+'/addtalk$',
        'studyjournal.talks.views.add_talk'),

    (r'^talk/'+talk_id+'/$',
        'studyjournal.talks.views.talk'),
    (r'^talk/'+talk_id+'/edit$',
        'studyjournal.talks.views.edit_talk'),
    (r'^talk/'+talk_id+'/addrating$',
        'studyjournal.talks.views.add_rating_to_talk'),
    (r'^talk/'+talk_id+'/rating'+rating_id+'/$',
        'studyjournal.talks.views.add_rating_to_talk'),
    (r'^talk/'+talk_id+'/addtotopic$',
        'studyjournal.talks.views.add_talk_to_topic'),

    (r'^talk-pdf/'+talk_id+'/'+width+'/$',
        'studyjournal.talks.views.talk_pdf'),

    (r'^topics/$',
        'studyjournal.topicalguide.views.index'),
    (r'^topics/add/$',
        'studyjournal.topicalguide.views.add_topic'),
    (r'^topics/edit'+topic_id+'/$',
        'studyjournal.topicalguide.views.edit_topic'),
    (r'^topic/'+topic_id+'/$',
        'studyjournal.topicalguide.views.topic'),
    (r'^topic/'+topic_id+'/addrt$',
        'studyjournal.topicalguide.views.add_related_topic'),
    (r'^topic/'+topic_id+'/addsr$',
        'studyjournal.topicalguide.views.add_scripture_entry'),
    (r'^topic/'+topic_id+'/sr'+entry_id+'/$',
        'studyjournal.topicalguide.views.add_scripture_entry'),
    (r'^topic/'+topic_id+'/addq$',
        'studyjournal.topicalguide.views.add_quote'),
    (r'^topic/'+topic_id+'/q'+entry_id+'/$',
        'studyjournal.topicalguide.views.add_quote'),
    (r'^topic/'+topic_id+'/addt$',
        'studyjournal.topicalguide.views.add_talk_entry'),
    (r'^topic/'+topic_id+'/t'+entry_id+'/$',
        'studyjournal.topicalguide.views.add_talk_entry'),

    (r'^scriptures/$',
        'studyjournal.topicalguide.views.scriptures'),

    (r'^callings/$',
        'studyjournal.talks.views.callings'),

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),

)

talks/models.py
from django.db import models
import datetime
from django.utils.safestring import SafeString


class Talk(models.Model):
    TYPE_CHOICES = (
            (u'GC', u'General Conference'), 
            (u'CES', u'CES Fireside'),
            (u'BYU', u'BYU Devotional'), 
            (u'BYUI', u'BYU-Idaho Devotional'),
            (u'CM', u'Church Magazine Article'),
            (u'RS', u'General Relief Society Meeting'),
            (u'YW', u'General Young Women Meeting'),
            (u'O', u'Other'),
            )

    speaker = models.ForeignKey('Person')
    # If speaker is Other, this field is used (soon to be removed...)
    speakername = models.CharField(max_length=100, blank=True)
    date = models.DateField('Date given')
    title = models.CharField(max_length=500, blank=True)
    text = models.TextField()
    topic = models.CharField(max_length=500, blank=True)
    type = models.CharField(max_length=5, choices=TYPE_CHOICES)
    externallink = models.CharField(max_length=500, blank=True)
    # This is looking forward, in case I want to download all of the audio
    # files (which I'm currently debating)
    audiofile = models.CharField(max_length=500, blank=True)
    audiolink = models.CharField(max_length=500, blank=True)

    def __unicode__(self):
        if self.speakername:
            return self.title+', '+self.speakername
        else:
            return self.title+', '+self.speaker.name()

    def pretty(self):
        return self.title+', '+str(self.date)+', '+self.type

    def date_string(self):
        return str(self.date)

    def get_rating(self):
        ratings = self.rating_set.all()
        if ratings:
            average = sum([int(r.rating) for r in ratings])/len(ratings)
            return '%d (%d)' % (average, len(ratings))
        else:
            return 'No ratings'


class Rating(models.Model):
    RATING_CHOICES = (
            (u'1', u'1'),
            (u'2', u'2'),
            (u'3', u'3'),
            (u'4', u'4'),
            (u'5', u'5'),
            )

    talk = models.ForeignKey('Talk')
    user = models.ForeignKey('auth.User')
    rating = models.CharField(max_length=1, choices=RATING_CHOICES)
    comment = models.TextField()


class Person(models.Model):
    GENDER_CHOICES = ((u'M', u'Male'), (u'F', u'Female'),)

    firstname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    suffix = models.CharField(max_length=10)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    wikipedia_bio = models.CharField(max_length=1000, blank=True)
    ga_bio = models.CharField(max_length=1000, blank=True)

    def name(self):
        if self.middlename == '_':
            middlename = ' '
        else:
            middlename = ' '+self.middlename+' '
        if self.suffix == '_':
            suffix = ''
        else:
            suffix = ', '+self.suffix
        return self.firstname+middlename+self.lastname+suffix

    def callings(self):
        callings = []
        for calling in self.calling_set.all():
            if len(callings) == 0:
                callings.append(calling)
            else:
                for i in range(len(callings)):
                    if calling.startdate < callings[i].startdate:
                        callings.insert(i, calling)
                        break
                else:
                    callings.append(calling)
        return ', '.join([x.__unicode__() for x in callings])

    def get_calling(self, date):
        for calling in self.calling_set.all():
            if not calling.enddate:
                enddate = datetime.date.today()
            else:
                enddate = calling.enddate
            startdate = calling.startdate
            if startdate <= date <= enddate:
                return calling.calling
        else:
            raise ValueError(self.name()+\
                    ' did not have a calling on '+str(date))

    def numtalks(self):
        return str(len(self.talk_set.all()))
    numtalks.short_description='Number of Talks'

    def __unicode__(self):
        return self.name()

    def average_rating(self):
        ratings = []
        for talk in self.talk_set.all():
            for rating in talk.rating_set.all():
                ratings.append(int(rating.rating))
        if not ratings:
            return 'No ratings'
        num = len(ratings)
        average = float(sum(ratings)) / num
        if average % 1 == 0.0:
            return '%d (with %d ratings)' % (average, num)
        else:
            return '%.1f (with %d ratings)' % (average, num)

    class Meta:
        ordering = ['lastname', 'firstname']
        verbose_name_plural = 'People'


class Calling(models.Model):
    CALLING_CHOICES = (
            (u'P',u'President of the Church'),
            (u'FC',u'First Counselor in the First Presidency'),
            (u'SC',u'Second Counselor in the First Presidency'),
            (u'C',u'Counselor in the First Presidency'),
            (u'A',u'Apostle'),
            (u'AT',u'Assistant to the Twelve'),
            (u'PS',u'Presidency of the Seventy'),
            (u'1S',u'First Quorum of the Seventy'),
            (u'2S',u'Second Quorum of the Seventy'),
            (u'AS',u'Area Seventy'),
            (u'PB',u'Presiding Bishop'),
            (u'PBRC',u'Presiding Bishopric'),
            (u'RSP',u'Relief Society General President'),
            (u'RSC',u'Relief Society General Presidency'),
            (u'YWP',u'Young Women General President'),
            (u'YWC',u'Young Women General Presidency'),
            (u'YMP',u'Young Men General President'),
            (u'YMC',u'Young Men General Presidency'),
            (u'SSP',u'Sunday School General President'),
            (u'SSC',u'Sunday School General Presidency'),
            (u'PC',u'Patriarch of the Church'),
            (u'O',u'Other'),
            )
    calling = models.CharField(max_length=4, choices=CALLING_CHOICES)
    # If calling is Other, this field is used
    othername = models.CharField(max_length=100, null=True, blank=True)
    startdate = models.DateField('Date Called')
    enddate = models.DateField('Date Released', null=True, blank=True)
    person = models.ForeignKey(Person)

    def __unicode__(self):
        if self.calling == 'O':
            return self.othername
        else:
            return self.get_calling_display()

    def pretty(self):
        if self.enddate:
            endstr = str(self.enddate)
        else:
            endstr = 'present'
        return self.__unicode__()+': '+str(self.startdate)+' - '+endstr

topicalguide/models.py
from django.db import models
from scriptures import split_for_sorting, get_link
from django.utils.safestring import SafeString

class Topic(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('auth.User')
    subheading = models.CharField(max_length=100, blank=True)
    indexname = models.CharField(max_length=50)
    notes = models.TextField(blank=True)
    last_modified = models.DateTimeField()
    related_topics = models.ManyToManyField('Topic')

    class Meta:
        ordering = ['indexname']

    def __unicode__(self):
        return self.indexname + ' (' + self.user.first_name + ')'

    def num_entries(self):
        return self.num_talks() + self.num_scriptures() + self.num_quotes()

    def scripture_references(self):
        refs = list(self.reference_set.all())
        refs.sort(key=lambda x: split_for_sorting(x.reference))
        return refs


class TalkEntry(models.Model):
    topic = models.ForeignKey('Topic')
    notes = models.TextField(blank=True)
    talk = models.ForeignKey('talks.Talk')
    quote = models.TextField(blank=True)

    def __unicode__(self):
        return self.talk.__unicode__()


class Quote(models.Model):
    topic = models.ForeignKey('Topic')
    notes = models.TextField(blank=True)
    person = models.ForeignKey('talks.Person')
    quote = models.TextField()
    source = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.person.__unicode__()


class Reference(models.Model):
    topic = models.ForeignKey('Topic')
    notes = models.TextField(blank=True)
    reference = models.CharField(max_length=150)

    def get_link(self):
        return SafeString(get_link(self.reference))

    def __unicode__(self):
        return self.reference
    

templates/talks/callings.html
{% extends "basetemplate.html" %}

{% block title %} Callings {% endblock %}

{% block content %}

<form action="" method="get">
	<table class=dateform>
		<col width=5%>
		<col width=5%>
		<tr>
			<td> Year: </td>
			<td><input type="text" name="year" value={{year}} /></td>
		</tr>
		<tr>
			<td> Month: </td>
			<td><input type="text" name="month" value={{month}} /></td>
		</tr>
		<tr>
			<td> Day: </td>
			<td><input type="text" name="day" value={{day}} /></td>
		</tr>
		<tr>
			<td><input type="submit" value="Go to Date" /></td><td></td>
		</tr>
	</table>
</form>

<table class=first_presidency>
	<thead>
		<th>
			First Presidency
		</th>
	</thead>
	<tbody>
		{% if callings.president %}
		<tr>
			<td><a href="/person/{{callings.president.id}}">{{ callings.president }}</a></td>
		</tr>
		{% endif %}
		{% if callings.first_counselor %}
		<tr>
			<td><a href="/person/{{callings.first_counselor.id}}">{{ callings.first_counselor }}</a></td>
		</tr>
		{% endif %}
		{% if callings.second_counselor %}
		<tr>
			<td><a href="/person/{{callings.second_counselor.id}}">{{ callings.second_counselor }}</a></td>
		</tr>
		{% endif %}
		{% if callings.extra_counselors %}
			{% for counselor in callings.extra_counselors %}
			<tr>
				<td><a href="/person/{{counselor.id}}">{{ counselor }}</a></td>
			</tr>
			{% endfor %}
		{% endif %}
	</tbody>
</table>

<table class=apostles>
	<thead>
		<th>
			Apostles
		</th>
	</thead>
	<tbody>
		{% for apostle in callings.apostles %}
		<tr>
			<td><a href="/person/{{apostle.id}}">{{ apostle }}</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>

<table class=presiding_bishopric>
	<thead>
		<th>
			Presiding Bishopric
		</th>
	</thead>
	<tbody>
		{% if callings.presiding_bishop %}
		<tr>
			<td><a href="/person/{{callings.presiding_bishop.id}}">{{ callings.presiding_bishop }}</a></td>
		</tr>
		{% endif %}
		{% if callings.presiding_bishopric %}
			{% for bishop in callings.presiding_bishopric %}
			<tr>
				<td><a href="/person/{{bishop.id}}">{{ bishop }}</a></td>
			</tr>
			{% endfor %}
		{% endif %}
	</tbody>
</table>

<table class=seventy>
	<thead>
		<th>
			Seventy
		</th>
	</thead>
	<tbody>
		{% for seventy in callings.seventy %}
		<tr>
			<td><a href="/person/{{seventy.id}}">{{ seventy }}</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/talks/people.html
{% extends "basetemplate.html" %}

{% block title %} People {% endblock %}

{% block content %}
{% if people_list %}
	<table class=people>
	<thead>
	<tr>
	{% for letter in people_list.letters %}
	<th onclick="toggle_people('{{ letter.letter }}')">
		{{ letter.letter }}
	</th>
	{% endfor %}
	</tr>
	</thead>
	</table>
	{% for letter in people_list.letters %}
		{% ifequal letter.letter "A" %}
			<ul class=show_people id={{ letter.letter }}>
		{% else %}
			<ul class=hide_people id={{ letter.letter }}>
		{% endifequal %}
			{% for person in letter.people %}
				<li><a href="/person/{{ person.id }}">{{ person.name }}</a></li>
			{% endfor %}
		</ul>
	{% endfor %}
{% else %}
	<p> No people! </p>
{% endif %}
{% endblock %}

templates/talks/person.html
{% extends "basetemplate.html" %}

{% block title %}{{ person.name }}{% endblock %}

{% block content %}
<h1>{{ person.name }}</h1>
<h3> Bios </h3>
<ul>
{% if person.wikipedia_bio %}
<li><a href="{{ person.wikipedia_bio }}">Wikipedia</a></li>
{% endif %}
{% if person.ga_bio %}
<li><a href="{{ person.ga_bio }}">Grampa Bill's G.A. Pages</a></li>
{% endif %}
</ul>
{% if callings %}
<h3> Callings </h3>
	<ul>
	{% for calling in callings %}
	<li>{{ calling.pretty }}</li>
	{% endfor %}
	</ul>
{% endif %}
<a href="/person/{{ person.id }}/edit">Edit {{ person.name }}'s information</a>
<h3> Talks </h3>
Average rating: {{ person.average_rating }}
<table>
	<thead>
		<th>Title</th>
		<th>Type</th>
		<th>Date</th>
		<th>Rating</th>
		<th>Topics</th>
		<th>Text</th>
		<th>Link</th>
	</thead>
	{% for talk in talks %}
		<tr>
			<td><a href="/talk/{{ talk.id }}">{{ talk.title }}</a></td>
			<td>{{ talk.get_type_display }}</td>
			<td>{{ talk.date_string }}</td>
			<td>{{ talk.get_rating }}</td>
			<td>{{ talk.talkentry_set.all|length }}</td>
			{% if talk.text %}
				<td><a href="/talk/{{ talk.id }}">Text</a></td>
			{% else %}
				<td>No text</td>
			{% endif %}
			{% if talk.externallink %}
				<td><a href="{{ talk.externallink }}">Link</a></td>
			{% else %}
				<td>No link</td>
			{% endif %}
		</tr>
	{% endfor %}
	<tr>
		<td><a href="addtalk">Add a talk</a></td>
		<td></td><td></td><td></td><td></td><td></td>
	</tr>
</table>
{% endblock %}

templates/talks/talk.html
{% extends "basetemplate.html" %}

{% block title %}{{ talk }}{% endblock %}

{% block content %}
{% if talk.title %}
<h1>{{ talk.title }}</h1>
{% else %}
<h1>No Title</h1>
{% endif %}
<a href='/person/{{ talk.speaker.id }}'>
{% if talk.speakername %}
<h3>{{ talk.speakername }} </h3>
{% else %}
<h3>{{ talk.speaker.name }}</h3>
{% endif %}
</a>
<h3>{{ talk.date }}</h3>
<h3>{{ talk.get_type_display }}</h3>
{% if link %}
<h4><a href={{ link }}>External Link</a></h4>
{% endif %}
<a href="edit">Edit talk information and text</a>
<table class="topicsfortalk">
	<thead>
		<th>Topics</th>
	</thead>
	<tbody>
		{% for entry in talk.talkentry_set.all %}
		<tr>
			<td>
				<a href="/topic/{{ entry.topic.id }}">{{ entry.topic }}</a>
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td>
				<form method="post" action="addtotopic">
				{{ topicform }}
				<input type="submit" name="submit" value="Add to topic" />
				</form>
			</td>
		</tr>
	</tbody>
</table>
<table class="ratings">
	<thead>
		<th colspan=5>Ratings</th>
	</thead>
	<tbody>
		{% for rating in ratings %}
		<tr>
			<td>
				{{ rating.rating }}
			</td>
			<td>
				{{ rating.user.first_name }}
			</td>
			<td>
				{{ rating.comment|linebreaks }}
			</td>
			<td>
				<a href="rating{{ rating.id }}">Edit</a>
			</td>
			<td>
				<form>
						<input type="button"
						onclick="confirm_delete('/talk/{{ talk.id }}',
						'this rating from {{ talk }}',
						'rating{{ rating.id }}')"
						class="table_button"
					   	value="Delete" />
				</form>
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td colspan=5>
				<a href="addrating">Add a rating</a>
			</td>
		</tr>
	</tbody>
</table>
<h3>Text:</h3>
<h4><a href=/talk-pdf/{{talk.id}}/2.1>View as pdf</a></h4>
{{ talk.text|linebreaks }}
{% endblock %}